### ISSUE TITLE
(blocked:mixed-content) for assets when hosting the website being an https proxy server/loadbalancer

### ISSUE THREAD

**Issue by wdekou** [AVONnadozie/LiteFrame#2]
# Problem 
When we host a LiteFrame website https://domain.com being an *https* proxy server, assets (eg, http://domain.com/assets/css/bootstrap.min.css) are generated using *http* which lead browsers (Chrome, Opera, Firefox) to issue  a (blocked:mixed-content) Status on assets preventing them to load. 

Web server involve: Apache and Nginx, 

Exceptions happen when you try to open a no secure website, That time assets load too because there are not protected.

# Solution

#1 Do not use hard link for asset: Do not include the hostname and protocol, give the asset path from the server root, 
#2 For the case where you will like to place assets on cdn give provide an env config for the cdn base hostname  like CDN_ROOT

**Comment by AVONnadozie** [comment]
The framework does not use hard links for assets, use the `asset` helper function to achieve this.

However, following your suggestions, the `asset` function has been updated to support URLs. You can set the `app.assets` in configuration or the default `APP_ASSETS` env value to your CDN URL to fix these issues
