### ISSUE TITLE
Security issue: "Preferably 777"

### ISSUE THREAD

**Issue by sbrl** [AVONnadozie/LiteFrame#4]
The documentation [here](https://avonnadozie.github.io/LiteFrame/) recommends that a permissions mode of 0777 is used.

I was curious about what this project is and what it does, but I'm going to stay _well_ away from any documentation that actually recommends 0777 as a serious permissions setting. This allows _anyone_ on a system to read and _write_ to a directory.

In addition, on files, it allows execution privileges, which is an additional security risk. For example, if an application accepts user input and saves it to a file with 0777 privileges, a malicious actor may be able to execute arbitrary code on the server!

Here are some good resources to learn about Linux permissions:

 - https://www.linux.com/learn/understanding-linux-file-permissions
 - https://www.digitalocean.com/community/tutorials/an-introduction-to-linux-permissions

Strong permission settings are an essential safeguard against attack.

**Comment by AVONnadozie** [comment]
Thank you! 
The documentation has been updated and the recommended permission is now 0755. 
All that is required is that the application should be able to write to the storage folder.

**Comment by sbrl** [comment]
Cool, thanks!
